
keep_alive_test:
	rm -f keep_alive_test.out
	g++ -o keep_alive_test.out keep_alive_test.cpp
	./keep_alive_test.out 
1_chatgpt:
	rm -f keep_alive_chatgpt_1.out
	g++ -o keep_alive_chatgpt_1.out keep_alive_chatgpt_1.cpp
	./keep_alive_chatgpt_1.out
2_chatgpt:
	rm -f keep_alive_chatgpt_2.out
	g++ -o keep_alive_chatgpt_2.out keep_alive_chatgpt_2.cpp
	./keep_alive_chatgpt_2.out