.PHONY: all clean
all:
	g++ -o main -C main.cpp encrypt.cpp socks5shadowsocks.cpp \
    -LD:\Qt\Qt6\Tools\mingw900_64\opt\lib -lssl \
    -LD:\Qt\Qt6\Tools\mingw900_64\opt\lib -lcrypto \
    -lws2_32