cares-basic:
	g++ -o cares-basic.out c-ares-name-to-host.cpp -lcares
	./cares-basic.out x.com
cares-select:
	g++ -o cares-select.out c-ares-select-input.cpp -lcares
	./cares-select.out x.com

cares-epoll:
	g++ -o cares-epoll.out c-ares-epoll.cpp -lcares
	./cares-epoll.out domain

cares-poll:
	g++ -o cares-poll.out c-ares-poll.cpp -lcares
	./cares-poll.out