.PHONY: thread_test

thread_test:
	g++ -o thread_test -C thread_test.cpp
openssl_test:
	g++ -o openssl_test -C openssl_test.cpp \
	-LD:\Qt\Qt6\Tools\mingw900_64\opt\lib -lssl \
    -LD:\Qt\Qt6\Tools\mingw900_64\opt\lib -lcrypto